In [58]:
import pandas as pd

path = '/content/BankChurners.csv'

df = pd.read_csv(path)
df.columns = df.columns.str.strip()

print("Here's the head:")
df.head()

Here's the head:

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

In [59]:
df.columns

Index(['CLIENTNUM', 'Attrition_Flag', 'Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio'],
      dtype='object')

In [60]:
df.isnull().sum()
df.isnull().mean() * 100

CLIENTNUM                   0.0
Attrition_Flag              0.0
Customer_Age                0.0
Gender                      0.0
Dependent_count             0.0
Education_Level             0.0
Marital_Status              0.0
Income_Category             0.0
Card_Category               0.0
Months_on_book              0.0
Total_Relationship_Count    0.0
Months_Inactive_12_mon      0.0
Contacts_Count_12_mon       0.0
Credit_Limit                0.0
Total_Revolving_Bal         0.0
Avg_Open_To_Buy             0.0
Total_Amt_Chng_Q4_Q1        0.0
Total_Trans_Amt             0.0
Total_Trans_Ct              0.0
Total_Ct_Chng_Q4_Q1         0.0
Avg_Utilization_Ratio       0.0
dtype: float64

In [61]:
print("Duplicate rows:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

Duplicate rows: 0

In [62]:
df['Credit_Limit'] = df['Credit_Limit'].astype(float)
df['Avg_Open_To_Buy'] = df['Avg_Open_To_Buy'].astype(float)

In [63]:
df.drop(columns=['CLIENTNUM'], errors='ignore', inplace=True)

In [64]:
# Handle categorical missing values explicitly
cat_missing_cols = ['Education_Level', 'Marital_Status', 'Income_Category']

for col in cat_missing_cols:
    df[col] = df[col].replace('Unknown', 'Missing')

In [65]:
# Create missing indicator flags
for col in cat_missing_cols:
    df[col + '_missing_flag'] = (df[col] == 'Missing').astype(int)

In [66]:
# Convert target to binary
df['Attrition_Flag'] = df['Attrition_Flag'].map({
    'Existing Customer': 0,
    'Attrited Customer': 1
})

In [67]:

print("\nFinal Missing Values:\n", df.isnull().sum())
print("\nFinal Dataset Shape:", df.shape)
print("\nData Types:\n", df.dtypes)

Final Missing Values:
 Attrition_Flag                  0
Customer_Age                    0
Gender                          0
Dependent_count                 0
Education_Level                 0
Marital_Status                  0
Income_Category                 0
Card_Category                   0
Months_on_book                  0
Total_Relationship_Count        0
Months_Inactive_12_mon          0
Contacts_Count_12_mon           0
Credit_Limit                    0
Total_Revolving_Bal             0
Avg_Open_To_Buy                 0
Total_Amt_Chng_Q4_Q1            0
Total_Trans_Amt                 0
Total_Trans_Ct                  0
Total_Ct_Chng_Q4_Q1             0
Avg_Utilization_Ratio           0
Education_Level_missing_flag    0
Marital_Status_missing_flag     0
Income_Category_missing_flag    0
dtype: int64

Final Dataset Shape: (10127, 23)

Data Types:
 Attrition_Flag                    int64
Customer_Age                      int64
Gender                           object
Dependent_count                   int64
Education_Level                  object
Marital_Status                   object
Income_Category                  object
Card_Category                    object
Months_on_book                    int64
Total_Relationship_Count          int64
Months_Inactive_12_mon            int64
Contacts_Count_12_mon             int64
Credit_Limit                    float64
Total_Revolving_Bal               int64
Avg_Open_To_Buy                 float64
Total_Amt_Chng_Q4_Q1            float64
Total_Trans_Amt                   int64
Total_Trans_Ct                    int64
Total_Ct_Chng_Q4_Q1             float64
Avg_Utilization_Ratio           float64
Education_Level_missing_flag      int64
Marital_Status_missing_flag       int64
Income_Category_missing_flag      int64
dtype: object

In [68]:
X = df.drop('Attrition_Flag', axis=1)
y = df['Attrition_Flag']

cat_cols = X.select_dtypes(include='object').columns
num_cols = X.select_dtypes(include=['int64', 'float64']).columns

In [70]:
cleaned_path = '/content/BankChurners_Cleaned.csv'
df.to_csv(cleaned_path, index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [71]:
from google.colab import files
files.download(cleaned_path)